[package]
name = "rune_factory3_trainer"
version = "0.3.2"
edition = "2021"
authors = ["sylvavv"]
publish = false
license = "MIT"

[lib]
name = "xinput1_4"
crate-type = ["cdylib"]

[dependencies]
minhook_raw = "0.3.0"
vcheat = "0.6.6"
hudhook = { version = "0.7.1", default-features = false, features = [
    "dx11",
] }

strum = "0.26.3"
strum_macros = "0.26.4"

[build-dependencies]
forward-dll-mini = "0.1.16"
