[package]
name = "rune_factory3_trainer"
version = "0.1.7"
edition = "2021"
authors = ["vSylva"]
publish = false
license = "MIT"

[lib]
name = "xinput1_4"
crate-type = ["cdylib"]

[dependencies]
vcheat = "=0.6.2"
minhook_raw = "=0.3.0"
hudhook = "=0.6.4"
strum = "=0.26.2"
strum_macros = "=0.26.2"

[build-dependencies]
forward-dll-mini = "=0.1.16"
