name: Rust

on:
  push:
    tags:
      - 'v[0-9]+.*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-upload:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: x86_64-pc-windows-msvc
            profile: minimal
            override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/xinput1_4.dll
