name: Rust

on:
  push:
    tags:
      - 'v[0-9]+.*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        rustup default stable-x86_64-pc-windows-msvc
        cargo build --release

    - name: Install parse-changelog
      uses: taiki-e/install-action@parse-changelog

    - name: Generate changelog
      run: parse-changelog CHANGELOG.md > CHANGELOG.txt

    - name: Upload file
      uses: softprops/action-gh-release@v1
      with:
        body_path: CHANGELOG.txt
        prerelease: false
        files: target/release/xinput1_4.dll
        fail_on_unmatched_files: true
